# используем язык java. Travis CI поддерживает другие языки тоже.

language: java
jdk:
  - openjdk12

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="fc1b9794-765b-4cad-bf58-c65e9229922f"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -235illino@gmail.com
    on_success: never # default: change
    on_failure: always # default,ult: always


